### ISSUE TITLE
Disable depreciation warnings in prod environment

### ISSUE THREAD

**Issue by groganz** [CampaignChain/campaignchain#261]

**Comment by ghostika** [comment]
@groganz you shouldn't use the debug component in app_prod as it will initialise additional debugger classes what will make the debug environment noticeably slower.
I would suggest either to use this 2 function call in the app.php 
```
error_reporting(E_ALL ^ E_DEPRECATED)
ini_set('display_errors', 0);
```
or mention it in the documentation and let the users decide, what kind of php setting would they want to use.
