### ISSUE TITLE
Windows Installation: Deprecation Notice and 'App' is not recognized

### ISSUE THREAD

**Issue by moustlant** [CampaignChain/campaignchain#390]
Hi everyone,

I'm trying to install CampaignChain on Windows 7. 

But I have some problem at this step:
`composer create-project --stability=dev campaignchain/campaignchain campaignchain dev-master`

Everything is ok until I write my parameters:
`
Creating the "app/config/parameters.yml" file
Some parameters are missing. Please provide them.
database_driver (pdo_mysql):
database_host (127.0.0.1): ********
database_port (null): ******
database_name (campaignchain_ce): 
database_user (root): ****
database_password (null): *****
java_path (/usr/bin/java): C:/Program Files/Java
mailer_transport (smtp): smtp
mailer_host (127.0.0.1): *****
mailer_user (null): ****
mailer_password (null): ******
mailer_sender_address (no-reply@example.com): ******
mailer_sender_name (CampaignChain): 
locale (en):
secret (ThisTokenIsNotSoSecretChangeIt):
debug_toolbar (true):
debug_redirects (false):
use_assetic_controller (true):
router.request_context.host (localhost):
router.request_context.scheme (http):
campaignchain.env (dev):
campaignchain.tracking.js_route (/tracking.js):
campaignchain.max_date_interval ('+2 years'):
campaignchain.theme.skin (skin-black):
> composer run-script campaignchain-setup
CampaignChain: Created configuration files.
Deprecation Notice: The callback CampaignChain\CoreBundle\Composer\ScriptHandler
::initKernel declared at C:\Users\bds\campaignchain\vendor\campaignchain\c
ore\Composer\ScriptHandler.php accepts a Composer\Script\CommandEvent but campai
gnchain-setup events use a Composer\Script\Event instance. Please adjust your ty
pe hint accordingly, see https://getcomposer.org/doc/articles/scripts.md#event-c
lasses in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Eve
ntDispatcher/EventDispatcher.php:314
> CampaignChain\CoreBundle\Composer\ScriptHandler::initKernel
Deprecation Notice: The callback Sensio\Bundle\DistributionBundle\Composer\Scrip
tHandler::buildBootstrap declared at C:\Users\bds\campaignchain\vendor\sen
sio\distribution-bundle\Sensio\Bundle\DistributionBundle\Composer\ScriptHandler.
php accepts a Composer\Script\CommandEvent but campaignchain-setup events use a
Composer\Script\Event instance. Please adjust your type hint accordingly, see ht
tps://getcomposer.org/doc/articles/scripts.md#event-classes in phar://C:/Program
Data/ComposerSetup/bin/composer.phar/src/Composer/EventDispatcher/EventDispatche
r.php:314
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
Deprecation Notice: The callback Sensio\Bundle\DistributionBundle\Composer\Scrip
tHandler::installRequirementsFile declared at C:\Users\bds\campaignchain\v
endor\sensio\distribution-bundle\Sensio\Bundle\DistributionBundle\Composer\Scrip
tHandler.php accepts a Composer\Script\CommandEvent but campaignchain-setup even
ts use a Composer\Script\Event instance. Please adjust your type hint accordingl
y, see https://getcomposer.org/doc/articles/scripts.md#event-classes in phar://C
:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/EventDispatcher/Event
Dispatcher.php:314
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFi
le
Deprecation Notice: The callback Sensio\Bundle\DistributionBundle\Composer\Scrip
tHandler::removeSymfonyStandardFiles declared at C:\Users\bds\campaignchai
n\vendor\sensio\distribution-bundle\Sensio\Bundle\DistributionBundle\Composer\Sc
riptHandler.php accepts a Composer\Script\CommandEvent but campaignchain-setup e
vents use a Composer\Script\Event instance. Please adjust your type hint accordi
ngly, see https://getcomposer.org/doc/articles/scripts.md#event-classes in phar:
//C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/EventDispatcher/Ev
entDispatcher.php:314
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::removeSymfonyStandard
Files
> app/console campaignchain:update:kernel
'app' is not recognized as an internal or external command,
operable program or batch file.
Script app/console campaignchain:update:kernel handling the campaignchain-setup
event returned with error code 1
Script composer run-script campaignchain-setup handling the post-install-cmd eve
nt returned with error code 1
`

Thank you for your help!

**Comment by groganz** [comment]
Sorry for the later reply. Please try again.

**Comment by groganz** [comment]
This should be fixed now. Please try again.

**Comment by philipihesiulo** [comment]
I have this same issue on my windows computer.  I there a fix for it?

**Comment by kakkarott** [comment]
me too
