### ISSUE TITLE
Adding FB or TW

### ISSUE THREAD

**Issue by ottermix** [CampaignChain/campaignchain#393]
I have an issue when using the community edition of CC.  It's related to the Hybrid oauth library but can't get around it with campaign chain config (and therefore can't use any of the OAuth stuff with CC).  I am getting errors like:

`external.ERROR: Authentication failed! Facebook returned an invalid user id. [] []`

and 

`{"exception":"[object] (CampaignChain\\CoreBundle\\Exception\\ExternalApiException(code: 5): Authentication failed! Twitter returned an error. 401 Unauthorized. at /opt/bitnami/apps/campaigns/htdocs/vendor/campaignchain/security-authentication-client-oauth/Authentication.php:123, Exception(code: 5): Authentication failed! Twitter returned an error. 401 Unauthorized. at /opt/bitnami/apps/campaigns/htdocs/vendor/hybridauth/hybridauth/hybridauth/Hybrid/Auth.php:169)"}`

I am using the latest version and installed from `dev-master`.  Is there a way I can get around this?  It is related to:

- https://github.com/hybridauth/hybridauth/issues/188

Cheers

**Comment by jasjitchopra** [comment]
+1 same issue here.

**Comment by groganz** [comment]
Change `router.request_context.scheme` to `https` in `app/config/parameters.yml`.

Also, make sure to provide the proper value for `router.request_context.host`, e.g. `www.example.com`.

**Comment by nguyencongvu** [comment]
My instance is latest dev-master 
I can add twitter but not facebook.
Error: Authentication failed! Facebook returned an invalid user id.

**Comment by iamdeadman** [comment]
@groganz tried setting the router.request_context.scheme to https, router.request_context.host to local.[*].com ( replacing * with a matching entry in /etc/hosts to test the facebook app's connection on localhost )  

But, still getting the same error returned from the application. Any more suggestions ? or ways to debug this issue?

**Comment by groganz** [comment]
This should be fixed by: https://github.com/CampaignChain/campaignchain/issues/423
