### ISSUE TITLE
Repeating campaigns should be displayed with relative dates

### ISSUE THREAD

**Issue by jasjitchopra** [CampaignChain/campaignchain#396]
Repeating campaigns should be displayed with relative dates.

Scheduled a twitter activity and it wont fire and does not even show on scheduled calendar.

Would be great to see more documentation around how to properly schedule repeating campaigns.
![capture](https://user-images.githubusercontent.com/11431799/26886513-39967fb8-4bc3-11e7-968f-e2f6257d1d9a.png)

**Comment by groganz** [comment]
This is fixed, but this related issue is new/open: https://github.com/CampaignChain/campaignchain/issues/403
