### ISSUE TITLE
Add facebook location

### ISSUE THREAD

**Issue by nguyencongvu** [CampaignChain/campaignchain#405]
I can add twitter but not Facebbok 

AppId and Secret ok 

Error return

ERROR - Authentication failed! Facebook returned an invalid user id. 
CRITICAL - Uncaught PHP Exception CampaignChain\CoreBundle\Exception\ExternalApiException: "Authentication failed! Facebook returned an invalid user id." at /opt/campaignchain/campaignchain/vendor/campaignchain/security-authentication-client-oauth/Authentication.php line 123

**Comment by kartik11** [comment]
Notice: Undefined index: oauth_token
500 Internal Server Error - ExternalApiException
1 linked Exception:Exception » 
I have faced while connect to Twitter, can you explain me how to connect to twitter.

**Comment by nguyencongvu** [comment]
Hi there, 
I connected twitter narutally (with key and secret).  
Setting website: http://mydomain:8000
Callback url: http://mydomain:8000/callbacl (no route callbacl actually), just type it

That's it

**Comment by kartik11** [comment]
Thanks for your response, i have connected to twitter and it's working. But still issues in FB. Can you share sample "Redirect URL", so i can update my FB app then go for rond of testing.

**Comment by iamdeadman** [comment]
I am also facing the same issue, did you find a solution to this facebook location issue.

**Comment by groganz** [comment]
I believe this was fixed with: https://github.com/CampaignChain/campaignchain/issues/423.
